// <auto-generated />
using System;
using Airport.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Airport.Api.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    [Migration("20260109195450_Add_Gate_Event")]
    partial class Add_Gate_Event
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Airport.Api.Models.Gate", b =>
                {
                    b.Property<int>("GateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gateId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GateId"));

                    b.Property<int>("Jetways")
                        .HasColumnType("integer")
                        .HasColumnName("jetways");

                    b.Property<int>("MaxPassengersPerHour")
                        .HasColumnType("integer")
                        .HasColumnName("maxPassengersPerHour");

                    b.Property<int>("TerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("terminalId");

                    b.HasKey("GateId");

                    b.HasIndex("TerminalId");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("Airport.Api.Models.GateEvent", b =>
                {
                    b.Property<int>("GateEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gateEventId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GateEventId"));

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<int>("GateEventTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("GateId")
                        .HasColumnType("integer")
                        .HasColumnName("gateId");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.HasKey("GateEventId");

                    b.HasIndex("GateEventTypeId");

                    b.HasIndex("GateId");

                    b.ToTable("GateEvents");
                });

            modelBuilder.Entity("Airport.Api.Models.GateEventType", b =>
                {
                    b.Property<int>("GateEventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gateEventTypeId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GateEventTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("GateEventTypeId");

                    b.ToTable("GateEventTypes");

                    b.HasData(
                        new
                        {
                            GateEventTypeId = 1,
                            Description = "Departure"
                        },
                        new
                        {
                            GateEventTypeId = 2,
                            Description = "Arrival"
                        });
                });

            modelBuilder.Entity("Airport.Api.Models.Hub", b =>
                {
                    b.Property<int>("HubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hubId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HubId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HubId");

                    b.ToTable("Hubs");
                });

            modelBuilder.Entity("Airport.Api.Models.Terminal", b =>
                {
                    b.Property<int>("TerminalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("terminalId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TerminalId"));

                    b.Property<int>("HubId")
                        .HasColumnType("integer")
                        .HasColumnName("hubId");

                    b.HasKey("TerminalId");

                    b.HasIndex("HubId");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("Airport.Api.Models.Gate", b =>
                {
                    b.HasOne("Airport.Api.Models.Terminal", "Terminal")
                        .WithMany("Gates")
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Airport.Api.Models.GateEvent", b =>
                {
                    b.HasOne("Airport.Api.Models.GateEventType", "GateEventType")
                        .WithMany()
                        .HasForeignKey("GateEventTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Airport.Api.Models.Gate", "Gate")
                        .WithMany("GateEvents")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gate");

                    b.Navigation("GateEventType");
                });

            modelBuilder.Entity("Airport.Api.Models.Terminal", b =>
                {
                    b.HasOne("Airport.Api.Models.Hub", "Hub")
                        .WithMany("Terminals")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Airport.Api.Models.Gate", b =>
                {
                    b.Navigation("GateEvents");
                });

            modelBuilder.Entity("Airport.Api.Models.Hub", b =>
                {
                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("Airport.Api.Models.Terminal", b =>
                {
                    b.Navigation("Gates");
                });
#pragma warning restore 612, 618
        }
    }
}
